package Exception;

public class Exception1 {
    public static void main(String[] args) {
        System.out.println("Hellooo");
        System.out.println("Helloooo");
        System.out.println("Hellooooo");
        System.out.println("Helloooooo");
        System.out.println("Hellooooooo");
        System.out.println("Helloooooooo");
        System.out.println("Hellooooooooo");
        int a;
        int b=23;
        int c=999;
        try{
            a=b+c;
            catch(Exception1 e){
            }
        }
    }
}
